[project]
name = "flash-moe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gguf>=0.17.1",
    "numpy>=2.4.2",
    "pyobjc-framework-metal>=12.1",
    "pyobjc-framework-metalkit>=12.1",
]
